### ISSUE TITLE
TODO de inúmeras alterações nos servidores

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#45]
Servidor ZE:

- [x] - Aumentar dano da molotov no ZM.
- [x] - Proteção do Mother Zombie no inicio do round por 30seg contra molotov.
- [x] - Anunciar que o jogador foi salvo da infecção caso seja um Top Defender.

Servidor TTT:

- [ ] - Eventos TTT. **[Ainda em planejamento]**
- [x] - Anti-Camping faz a vida do jogador ir até 0 (morte) ao invés de parar em 15.
- [ ] - Modo especial vts a cada X segundos 2 jogadores trocam de lugar.
- [x] - Buffar vida do Minion (macaco) no round Nemesis. Cada kill o hp dele regenera.
- [ ] - Vips podem abrir o vote de VTS a cada X minutos. **[Ainda em planejamento]**
- [ ] - Alterar regra do jogo de TTT para o jogo acabar se todos os inocentes morrerem, mesmo que ainda reste algum detetive vivo.

Sugestões de novas adições ao issue devem ser feitas pelo Discord no canal **#sugestoes**.

**Comment by lucaslinha** [comment]
Não sei se precisa de votação, mas a minha sugestão do modo aquecimento no ZE ainda ta de pe ? Para ressaltar: Não nasce zm ate 7 jogadores junto dos ct imortais e na mensagem de alerta aparece "Aguardando mais X jogadores para começar."  (Proposito disso é que ze com pouco player é uma merda.)

**Comment by danielhidalgojunior** [comment]
Dano no molotov é nice, mas deveria ser relativo ao mapa já q muitos mapas setam a vida máxima do zm.
Anunciar q o cara foi salvo da infecção pro ser top defender é algo q deveria ter desde o início... Até há um tempo nem eu sabia q ser top 1 te salvava da infecção

**Comment by danielhidalgojunior** [comment]
Esse modo de tp do ttt, poderia trocar sempre que alguém morrer ao invés de por tempo

**Comment by danielhidalgojunior** [comment]
Regenerar vida do macaco sim, adicionar mais vida nao

**Comment by danielhidalgojunior** [comment]
Esse negócio de acabar o jogo quando n tem mais inocente era pra ser padrão, n sei pq tá do outro jeito

**Comment by hcjordao** [comment]
@danielhidalgojunior acho molotov com bastante dano é nice. O objetivo do humano é sair matando o zm. Como a facada é ativavel por shop, acho que o meio de suprir a falta de kills por facada é possibilitando os humanos de matarem na molotov, isso junto com a proteção de molotov para mothers para não ficar broken.

**Comment by hcjordao** [comment]
Sempre que alguem morrer é interessante, mas acho mais daora ser por tempo tbm. Imagina o 1 v 1 com o tp. Pode ser algo tbm que a seja logaritmico tbm tempo do tp vai diminuindo ate ficar constante. Exemplo começa sendo a cada 20 segundos e vai diminuindo até chegar em uns 10 segundos. Não sei se vai dar dor de cabeça tbm nos jogadores.

**Comment by hcjordao** [comment]
Se a vida do macaco não aumentar o macaco vai ser meio useless não? Tu virando macaco tu morre 100% do tempo. Dependendo do mapa tu tem mais chance especialmente em mapa fechado como closequarters. Em mapas abertos = 0 chance.

**Comment by alminha021** [comment]
Random tp, seria bom se fosse sempre um valor aleatório entre 10 e 15 seg. 

Macaco enche a vida máxima se tiver pouca vida inicial. (Atualmente)
Ou
Regenera somente se já começar com a vida razoavelmente alta.

**Comment by alminha021** [comment]
1x1 de faca pode ser , mas só com todos os mortos identificados pra não dah problema com a essência do modo .

**Comment by hcjordao** [comment]
É isso de knife fight so se tiver todos os inos identificados se nao tu meio que da pro inocente que o proximo cara que ele ver ele pode matar. Nao sei se vai ficar boring no 1 v 1, talvez so se forem 2 perdidos que nao conhecem os mapas

**Comment by danielhidalgojunior** [comment]
Bota dano no molotov em escape tbm, very nice

**Comment by quasemago** [comment]
Ta maluco, nope

**Comment by quasemago** [comment]
@hcjordao essa proteção do motherzombie contra molotov seria valida também para o ZE?

**Comment by hcjordao** [comment]
So pra zm

**Comment by quasemago** [comment]
Mudanças para o TTT paradas devido ao fechamento do servidor.
